# Render Blueprint para CELEX: Postgres + FastAPI + Next.js

databases:
  - name: celex-db
    region: oregon
    plan: basic-1gb

services:
  # === Backend FastAPI ===
  - type: web
    name: celex-backend
    runtime: python
    region: oregon
    rootDir: back-celex
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: celex-db
          property: connectionString
      - key: ENV
        value: production

  # === Frontend Next.js (SSR) ===
  - type: web
    name: celex-frontend
    runtime: node
    region: oregon
    rootDir: front-celex
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_HOST
        fromService:
          name: celex-backend
          type: web
          property: host
      - key: INTERNAL_API_HOSTPORT
        fromService:
          name: celex-backend
          type: web
          property: hostport
      - key: NODE_VERSION
        value: 20
